### PR TITLE
Add readme.md

### PR DESCRIPTION
**Pull request by CapriciousRebel**
I have edited the readme.md and I request you to merge these two branches together.

### CODE REVIEW

**Review by ayanchoudhary — CHANGES_REQUESTED** [review]
try adding some description for some of the major features and list out the tech stack separately from the remaining text. Also add the steps for setting up your repo(i.e how someone else will run your game/ share the installer/binary)

**Comment by CapriciousRebel** [comment]
I actually haven't yet figured out how the game will be run. 
Also, I plan to add the major features as I add them to the game in the future.

**Comment by ayanchoudhary** [comment]
But you might have still thought of some features to make your game stand out, mention those. And did you have a project meeting? if yes then mention the architecture you decided otherwise put it after the project meeting

**Comment by CapriciousRebel** [comment]
We didn't yet have a project meeting where we decided the architecture
I'll add the features though.

**Comment by CapriciousRebel** [comment]
I have updated the readme.md file with the features. Kindly review it .

**Review by ayanchoudhary — APPROVED** [review]

**Pull request merged**
